### ISSUE TITLE
More informative Dust.js errors

### ISSUE THREAD

**Issue by abovebored** [dadi/web#150]
If you have a syntax error with Dust.js it tells you which line and col, but not the file where the error is located in the workspace. Example:

`/workspace/pages/index.dust`

```dust.js
{>"partials/header" /}

{#posts.results}
    {>"partials/post" /}
{/foobar} <<<<<<<<<<<<<<<<<<<<<< Error here

{>"partials/pagination" 
    currentPage=posts.metadata.page
    totalPages=posts.metadata.totalPages
/}

{>"partials/footer" /}
```

```bash
[2017-04-11 11:48:10.409] [LOG]   SyntaxError: Expected end tag for posts.results but it was not found. At line : 5, column : 10
    at Object.compiler.compile (/Users/Dave/Repos/web/node_modules/dustjs-linkedin/lib/compiler.js:34:13)
    at Object.Dust.dust.onLoad (/Users/Dave/Repos/web/dadi/lib/dust/index.js:31:25)
    at /Users/Dave/Repos/web/node_modules/dustjs-linkedin/lib/dust.js:180:18
    at Chunk.map (/Users/Dave/Repos/web/node_modules/dustjs-linkedin/lib/dust.js:722:7)
    at load (/Users/Dave/Repos/web/node_modules/dustjs-linkedin/lib/dust.js:154:22)
    at Object.dust.render (/Users/Dave/Repos/web/node_modules/dustjs-linkedin/lib/dust.js:97:7)
    at Dust.render (/Users/Dave/Repos/web/dadi/lib/dust/index.js:128:8)
    at View.render (/Users/Dave/Repos/web/dadi/lib/view/index.js:36:10)
    at loadData (/Users/Dave/Repos/web/dadi/lib/controller/index.js:206:10)
    at /Users/Dave/Repos/web/dadi/lib/controller/index.js:387:7
    at /Users/Dave/Repos/web/node_modules/async/lib/async.js:52:16
    at Immediate.<anonymous> (/Users/Dave/Repos/web/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
```

**Comment by abovebored** [comment]
<img width="511" alt="screen shot 2017-04-12 at 20 10 44" src="https://cloud.githubusercontent.com/assets/649231/24975024/2314ed66-1fbc-11e7-8a8c-7812ef26bb9d.png">

**Comment by abovebored** [comment]
I noticed incidentally, the `dust.onLoad` function we're attaching our callback errors to ([here](https://github.com/dadi/web/blob/00b9563cdd7503793e00d0816d7ee9f8adb8b6a8/dadi/lib/dust/index.js#L19)) is designed to pass-back a string only when combined with dust's own `ERROR` flag, so although it's logging to our system correctly, dust's log reports:

```
[DUST:ERROR] Rendering failed with error `[object Object]`
```

Not sure if this matters and/or would require a more comprehensive rework.
