### ISSUE TITLE
Handle incomplete datasource responses

### ISSUE THREAD

**Issue by fra967** [dadi/web#182]
Sometimes a datasource returns invalid or truncated json and parsing fails in Web 1.11.0
https://github.com/dadi/web/blob/v1.11.0/dadi/lib/datasource/route-validator.js#L28

Error example:
```
[2017-06-13 09:54:07.418] [LOG]   SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /dadi/web/node_modules/@dadi/web/dadi/lib/controller/index.js:345:92
    at dataCache.getFromCache (/dadi/web/node_modules/@dadi/web/dadi/lib/providers/remote.js:199:28)
    at RedisRStream.stream.on (/dadi/web/node_modules/@dadi/web/dadi/lib/cache/datasource.js:119:14)
    at emitNone (events.js:86:13)
    at RedisRStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

It would be useful to handle this json parsing error and log the offending datasource details

**Comment by fra967** [comment]
Let's also try to identify whether the truncated json is coming from Redis or directly from API

**Comment by jimlambie** [comment]
Closed by https://github.com/dadi/web/commit/1255df397e67b1c574d5cb23586909dd41309e48
