### ISSUE TITLE
Static assets 404 error crashes app

### ISSUE THREAD

**Issue by abovedave** [dadi/web#306]
Take a `page` with some images on which *do not* exist in the `public` folder:

```
 <img src="/assets/img/foo.jpg">
 <img src="/assets/img/foo2.jpg">
 <img src="/assets/img/foo3.jpg">
 <img src="/assets/img/foo4.jpg">
```

Visiting the page in browser will crash the app:

```
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:440:15)
    at Stream.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:96:13)
    at Stream.emit (events.js:188:7)
    at drain (/app/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/app/node_modules/through/index.js:45:5)
    at Stream.write (/app/node_modules/@dadi/web/dadi/lib/view/public.js:204:12)
    at Stream.stream.write (/app/node_modules/through/index.js:26:11)
    at ReadStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:2018:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)
```

**Comment by jimlambie** [comment]
@abovedave  this looks to be resolved, can you confirm and close?

```
04:38:31.358Z  INFO dadi-web: GET / 200 10ms (module=router)
04:38:31.408Z  INFO dadi-web: GET /assets/img/foo.jpg 404 5ms (module=router)
04:38:31.426Z  INFO dadi-web: GET /assets/img/foo2.jpg 404 1ms (module=router)
04:38:31.435Z  INFO dadi-web: GET /assets/img/foo3.jpg 404 1ms (module=router)
04:38:31.443Z  INFO dadi-web: GET /assets/img/foo4.jpg 404 1ms (module=router)
```

**Comment by abovedave** [comment]
Yes I have't seen it for a long time, let's reopen if it comes up again.
