### ISSUE TITLE
Broken setup

### ISSUE THREAD

**Issue by rayanfer32** [dadi/web#505]
```sh
rayanf@dell3558:~$ npm --version
6.14.11
rayanf@dell3558:~$ node --version
v14.16.0
```
```bash
rayanf@dell3558:~$ dadi
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/eduardoboucas/Sites/cli/wrapper/updater.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by rayanfer32** [comment]
Setup halts after showing `\ Checking the available versions of DADI Web` and  `dadi-web` folder is completely empty
**Error Logs:**
```sh
C:\ReactDev\Edge dadi>npx dadi-cli web new
? The target directory (C:\ReactDev\Edge dadi) is not empty. Would you like to
proceed? Yes
\ Checking the available versions of DADI Web
C:\ReactDev\Edge dadi>ls
dadi-web

C:\ReactDev\Edge dadi>npx dadi-cli web new

```
