### ISSUE TITLE
Capture event that triggers error

### ISSUE THREAD

**Issue by mingard** [dadi/web#98]
Currently when an event triggers an error, the event itself is not capture. Propose adding this to the logging

```json
{"name":"dadi-web","hostname":"ip-172-31-12-39","pid":19405,"level":50,"module":"event","msg":"{ [TypeError: Cannot read property 'urls' of undefined] statusCode: 404 }","time":"2016-11-16T13:41:54.265Z","v":0}
```

**Comment by fra967** [comment]
As part of this ticket, it would be important that event errors do not crash the service but are always caught

**Comment by jimlambie** [comment]
```
{"name":"dadi-web","hostname":"","pid":34824,"level":50,"module":"event","event":"test_event_error","page":"test","url":"/test","params":{"one":1},"options":{"eventPath":"/web/test/app/events"},"msg":"Error\n    at new Event (/web/test/app/events/test_event_error.js:13:13)\n    at module.exports (/web/test/app/events/test_event_error.js:20:12)\n    at Event.run (/web/dadi/lib/event/index.js:33:21)\n    at Context.<anonymous> (/web/test/unit/event.js:104:14)\n    at callFnAsync (/usr/local/lib/node_modules/mocha/lib/runnable.js:357:21)\n    at Test.Runnable.run (/usr/local/lib/node_modules/mocha/lib/runnable.js:309:7)\n    at Runner.runTest (/usr/local/lib/node_modules/mocha/lib/runner.js:428:10)\n    at /usr/local/lib/node_modules/mocha/lib/runner.js:534:12\n    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:348:14)\n    at /usr/local/lib/node_modules/mocha/lib/runner.js:358:7\n    at next (/usr/local/lib/node_modules/mocha/lib/runner.js:284:14)\n    at Immediate.<anonymous> (/usr/local/lib/node_modules/mocha/lib/runner.js:326:5)\n    at runCallback (timers.js:666:20)\n    at tryOnImmediate (timers.js:639:5)\n    at processImmediate [as _immediateCallback] (timers.js:611:5)","time":"2017-06-27T10:48:46.423Z","v":0}
```

**Comment by jimlambie** [comment]
Closed by https://github.com/dadi/web/commit/1255df397e67b1c574d5cb23586909dd41309e48
